In [11]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[4,5,4],[3,3,5],[0,0,1]])
result=[]
for i in range(len(arr1)):
    row=[]
    for j in range(len(arr1[0])):
        row.append(arr1[i][j]+arr2[i][j])
    result.append(row)


for i in result:
    for j in i:
        print(j,end=" ")
    print()


5 7 7 
7 8 11 
7 8 10 


In [8]:
#simple way of adding matrix
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[4,5,4],[3,3,5],[0,0,1]])
print("result",arr1+arr2)

result [[ 5  7  7]
 [ 7  8 11]
 [ 7  8 10]]


In [9]:
#multiplication
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[4,5,4],[3,3,5],[0,0,1]])
result=np.dot(arr1,arr2)
print(result)

[[10 11 17]
 [31 35 47]
 [52 59 77]]


In [12]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[4,5,4],[3,3,5],[0,0,1]])
result=np.transpose(arr1)
print(result)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#multiplication using nested loops
#transpose
