In [4]:
import numpy as np
arr=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]],dtype=complex)
print(arr)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [5]:
y=np.zeros((2,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
y=np.zeros((2,3),dtype=np.int32)
print(y)

[[0 0 0]
 [0 0 0]]


In [7]:
a=np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
import numpy as np
arr=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
for i in arr:
    for j in i:
        print(j,end=" ")
    print()

1 2 3 
4 5 6 
7 8 9 
